import pickle

dict_of_pickup_lines = pickle.load(open('pickuplines.pickle', 'rb'))
dict_of_olin = pickle.load(open('olinlines.pickle', 'rb'))
dict_of_star_wars = pickle.load(open('star_wars.pickle', 'rb'))
dict_of_music = pickle.load(open('music.pickle', 'rb'))
dict_of_HIMYM = pickle.load(open('HIMYM.pickle', 'rb'))
dict_of_GOT = pickle.load(open('GOT.pickle', 'rb'))
dict_of_disney = pickle.load(open('disney.pickle', 'rb'))
dict_of_biochem = pickle.load(open('biochem.pickle', 'rb'))
dict_of_accountant = pickle.load(open('accountant.pickle', 'rb'))
dict_of_animal = pickle.load(open('animal.pickle', 'rb'))
dict_of_art = pickle.load(open('art.pickle', 'rb'))
dict_of_baseball = pickle.load(open('baseball.pickle', 'rb'))
dict_of_beach = pickle.load(open('beach.pickle', 'rb'))
dict_of_basketball = pickle.load(open('basketball.pickle', 'rb'))
dict_of_books = pickle.load(open('books.pickle', 'rb'))
dict_of_car = pickle.load(open('car.pickle', 'rb'))
dict_of_chocolate = pickle.load(open('chocolate.pickle', 'rb'))
dict_of_coffee = pickle.load(open('coffee.pickle', 'rb'))
dict_of_doctor = pickle.load(open('doctor.pickle', 'rb'))
dict_of_dentist = pickle.load(open('dentist.pickle', 'rb'))
dict_of_dogs = pickle.load(open('dogs.pickle', 'rb'))
dict_of_engineer = pickle.load(open('engineer.pickle', 'rb'))
dict_of_environmental = pickle.load(open('environmental.pickle', 'rb'))
dict_of_firefighter =pickle.load(open('firefighter.pickle', 'rb'))
dict_of_fitness =pickle.load(open('fitness.pickle', 'rb'))
dict_of_golf = pickle.load(open('golf.pickle', 'rb'))
dict_of_football = pickle.load(open('football.pickle', 'rb'))
dict_of_history = pickle.load(open('history.pickle', 'rb'))
dict_of_hockey = pickle.load(open('hockey.pickle', 'rb'))
dict_of_lawyer = pickle.load(open('lawyer.pickle', 'rb'))
dict_of_LOTR = pickle.load(open('LOTR.pickle', 'rb'))
dict_of_math = pickle.load(open('math.pickle', 'rb'))
dict_of_military = pickle.load(open('military.pickle', 'rb'))
dict_of_nerdy = pickle.load(open('nerdy.pickle', 'rb'))
dict_of_pizza = pickle.load(open('pizza.pickle', 'rb'))
dict_of_policeofficer = pickle.load(open('policeofficer.pickle', 'rb'))
dict_of_psychology = pickle.load(open('psychology.pickle', 'rb'))
dict_of_robot =pickle.load(open('robot.pickle', 'rb'))
dict_of_scifi = pickle.load(open('scifi.pickle', 'rb'))
dict_of_tallperson = pickle.load(open('tallperson.pickle', 'rb'))
dict_of_soccer = pickle.load(open('soccer.pickle', 'rb'))
dict_of_tennis = pickle.load(open('tennis.pickle', 'rb'))
dict_of_walkingdead = pickle.load(open('walkingdead.pickle', 'rb'))
dict_of_volleyball = pickle.load(open('volleyball.pickle', 'rb'))
dict_of_yoga = pickle.load(open('yoga.pickle', 'rb'))
# dict_of_all = dict_of_pickup_lines + dict_of_olin + dict_of_star_wars + dict_of_music + dict_of_HIMYM + dict_of_GOT + dict_of_disney + dict_of_biochem + dict_of_accountant + 
# dict_of_animal + dict_of_art + dict_of_baseball + dict_of_beach + dict_of_basketball + dict_of_books + dict_of_car + dict_of_chocolate + dict_of_coffee + dict_of_doctor + dict_of_dentist + dict_of_dogs
# dict_of_engineer + dict_of_environmental + dict_of_firefighter + dict_of_fitness + dict_of_golf + dict_of_football + dict_of_history + dict_of_hockey + dict_of_lawyer
# + dict_of_LOTR + dict_of_math + dict_of_military + dict_of_nerdy + dict_of_pizza + dict_of_policeofficer + dict_of_psychology + dict_of_robot + dict_of_scifi +
# dict

print(len(dict_of_pickup_lines))
